### ISSUE TITLE
Error when trying to deploy

### ISSUE THREAD

**Issue by ejramalho** [bitbull-team/aws-rds-autoscaling#2]
After run make deploy we got the error message below:

An error occurred: IamRoleLambdaExecution - Resource  must be in ARN format or "*"..

**Comment by daaru00** [comment]
Hi @ejramalho ,

how do you set the env variable `NotificationSNS`? Are you using an ARN or the notification stream name?

The IAM role is configured in this way:
```
    - Effect: "Allow"
      Action:
        - "route53:ChangeResourceRecordSets"
      Resource: "arn:aws:route53:::hostedzone/${self:custom.HostedZoneId}"
    - Effect: "Allow"
      Action:
        - "rds:ModifyDBInstance"
      Resource: "arn:aws:rds:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:db:${self:custom.InstanceIdentifier}"
    - Effect: "Allow"
      Action:
        - "SNS:Publish"
      Resource: "${self:custom.NotificationSNS}"
```
check ARN is properly generated based on the configuration you entered and make sure you have set all variables inside [environment file](https://github.com/bitbull-team/aws-rds-autoscaling/blob/master/environment.sample).
